### PR TITLE
Update CC text to be recognizable by GitHub

### PR DESCRIPTION
**Pull request by cjmaxik**
Currently, GitHub doesn't see the license if it has "Creative Commons" in the header. The license itself doesn't have "Creative Commons" in the header anyway.

### CODE REVIEW

**Comment by idleberg** [comment]
I ran a quick test on the first license modified in the PR and didn't notice any difference. To make sure we're talking about the same thing, your expectation is that the correct license is shown in the highlighted portion of the screenshot, right?

Screenshot 2023-11-06 at 21 50 00

When you tested this, can you rule out that the license was discovered elsewhere, e.g. using the SPDX-identifier in a `package.json`?

**Comment by cjmaxik** [comment]
Sorry for the confusion, let me clarify the issue.
Currently, GitHub can show the license by its name (if you have a common one, that is). With the current text from this repo, it will show it as **Unknown**, but with the correct one it will show its name (shown below).

Incorrect:
image
image

Correct:
image
image

**Comment by idleberg** [comment]
Thanks for clarifying. Do you notice anything unusual in the [test-repository](https://github.com/idleberg/license-test), because it doesn't seem to work.

**Comment by cjmaxik** [comment]
I think it starts to classify the license when you have more than one in one repo.

**Comment by idleberg** [comment]
While I still couldn't produce the result myself, I found a license that works without your proposed changes

image

https://github.com/goldbergyoni/nodebestpractices/blob/master/LICENSE

**Pull request closed without merging**
